import { Injectable } from "@angular/core";

@Injectable({
  providedIn: "root"
})
export class DataService {
  public items: any = [];

  constructor() {
    this.items = [
      { title: "one" },
      { title: "two" },
      { title: "three" },
      { title: "four" },
      { title: "five" },
      { title: "six" }
    ];
  }

  filterItems(searchTerm:any) {
    return this.items.filter((item:any) => {
      return item.title.toLowerCase().indexOf(searchTerm.toLowerCase()) > -1;
    });
  }

   well_list = [
    {
      "wellId": 1,
      "wellName": "Apache 24 FED 11",
      "dateTime": "2020-04-14 13:14:59",
      "commsStatus": "Comms Established",
      "controllerStatus": "Shutdown",
      "spm": 50.0,
      "pumpFillage": 50.0,
      "inferredProduction": 32.5,
      "effectiveRuntimePercentage": 20,
      "cyclesToday": 23.5,
      "structuralLoadPercentage": 23.5,
      "minMaxloadPercentage": 23.5,
      "gearBoxLoadPercentage": 23.5,
      "rodStressPercentage": 23.5,
      "noOfAlerts": 2,
      "wellStatus": "Optimum Pumping",
      "avgSpm": "5.5 spm",
      "wellState": "Pumping Normal State",
      "pumpCardDiagnistics": "Normal",
      "pumpDisplacement": "278.0 bbls/day",
      "isWellOffline": false,
      "surfaceUnitInformation": "",
      "lastScan": "",
      "gatewayId": "",
      "strokeLengthInInches": 5,
      "tubingHeadPressure": "10psi",
      "casingHeadPressure": "8psi",
      "calculatedPumpIntakePressure": "10psi",
      "currentFluidLoad": 100,
      "downholeCardAreaInSqInch": 25,
      "pumpInfo": {
        "pumpId": "p01",
        "rodDetails": ""
      },
      "pumpDepthInFt": 10,
      "pumpType": "Steel",
      "lastWellTestData": {
        "testGasData": 146,
        "testOil": 46.41,
        "testWater": 82.68,
        "testGross": 109.1,
        "lastReceivedDtTime": "12/02/2023 12:00:00 AM"
      }
    },
    {
      "wellId": 2,
      "wellName": "Jones 2-15-022BH",
      "dateTime": "2020-04-14 13:14:59",
      "commsStatus": "Comms Failed 2020-04-14",
      "controllerStatus": "Hand(Manual)",
      "spm": 50.0,
      "pumpFillage": 50.0,
      "inferredProduction": 32.5,
      "effectiveRuntimePercentage": 20,
      "cyclesToday": 23.5,
      "structuralLoadPercentage": 23.5,
      "minMaxloadPercentage": 23.5,
      "gearBoxLoadPercentage": 23.5,
      "rodStressPercentage": 23.5,
      "noOfAlerts": 2,
      "wellStatus": "Optimum Pumping",
      "avgSpm": "5.5 spm",
      "wellState": "Pumping Normal State",
      "pumpCardDiagnistics": "Normal",
      "pumpDisplacement": "278.0 bbls/day",
      "isWellOffline": false,
      "surfaceUnitInformation": "",
      "lastScan": "",
      "gatewayId": "",
      "strokeLengthInInches": 5,
      "tubingHeadPressure": "10psi",
      "casingHeadPressure": "8psi",
      "calculatedPumpIntakePressure": "10psi",
      "currentFluidLoad": 100,
      "downholeCardAreaInSqInch": 25,
      "pumpInfo": {
        "pumpId": "p01",
        "rodDetails": ""
      },
      "pumpDepthInFt": 10,
      "pumpType": "Steel",
      "lastWellTestData": {
        "testGasData": 146,
        "testOil": 46.41,
        "testWater": 82.68,
        "testGross": 109.1,
        "lastReceivedDtTime": "12/02/2023 12:00:00 AM"
      }
    },
    {
      "wellId": 3,
      "wellName": "Apache 24 FED 11",
      "dateTime": "2020-04-14 13:14:59",
      "commsStatus": "Comms Failed 2020-04-14",
      "controllerStatus": "Auto",
      "spm": 50.0,
      "pumpFillage": 50.0,
      "inferredProduction": 32.5,
      "effectiveRuntimePercentage": 20,
      "cyclesToday": 23.5,
      "structuralLoadPercentage": 23.5,
      "minMaxloadPercentage": 23.5,
      "gearBoxLoadPercentage": 23.5,
      "rodStressPercentage": 23.5,
      "noOfAlerts": 4,
      "wellStatus": "Under Pumping",
      "avgSpm": "5.5 spm",
      "wellState": "Pumping Normal State",
      "pumpCardDiagnistics": "Normal",
      "pumpDisplacement": "278.0 bbls/day",
      "isWellOffline": false,
      "surfaceUnitInformation": "",
      "lastScan": "",
      "gatewayId": "",
      "strokeLengthInInches": 5,
      "tubingHeadPressure": "10psi",
      "casingHeadPressure": "8psi",
      "calculatedPumpIntakePressure": "10psi",
      "currentFluidLoad": 100,
      "downholeCardAreaInSqInch": 25,
      "pumpInfo": {
        "pumpId": "p01",
        "rodDetails": ""
      },
      "pumpDepthInFt": 10,
      "pumpType": "Steel",
      "lastWellTestData": {
        "testGasData": 146,
        "testOil": 46.41,
        "testWater": 82.68,
        "testGross": 109.1,
        "lastReceivedDtTime": "12/02/2023 12:00:00 AM"
      }
    },
    {
      "wellId": 4,
      "wellName": "Apache 24 FED 11",
      "dateTime": "2020-04-14 13:14:59",
      "commsStatus": "Comms Failed 2020-04-14",
      "controllerStatus": "Auto",
      "spm": 50.0,
      "pumpFillage": 50.0,
      "inferredProduction": 32.5,
      "effectiveRuntimePercentage": 20,
      "cyclesToday": 23.5,
      "structuralLoadPercentage": 23.5,
      "minMaxloadPercentage": 23.5,
      "gearBoxLoadPercentage": 23.5,
      "rodStressPercentage": 23.5,
      "noOfAlerts": 5,
      "wellStatus": "Optimum Pumping",
      "avgSpm": "5.5 spm",
      "wellState": "Pumping Normal State",
      "pumpCardDiagnistics": "Normal",
      "pumpDisplacement": "278.0 bbls/day",
      "isWellOffline": false,
      "surfaceUnitInformation": "",
      "lastScan": "",
      "gatewayId": "",
      "strokeLengthInInches": 5,
      "tubingHeadPressure": "10psi",
      "casingHeadPressure": "8psi",
      "calculatedPumpIntakePressure": "10psi",
      "currentFluidLoad": 100,
      "downholeCardAreaInSqInch": 25,
      "pumpInfo": {
        "pumpId": "p01",
        "rodDetails": ""
      },
      "pumpDepthInFt": 10,
      "pumpType": "Steel",
      "lastWellTestData": {
        "testGasData": 146,
        "testOil": 46.41,
        "testWater": 82.68,
        "testGross": 109.1,
        "lastReceivedDtTime": "12/02/2023 12:00:00 AM"
      }
    },
    {
      "wellId": 5,
      "wellName": "Apache 24 FED ",
      "dateTime": "2020-04-14 13:14:59",
      "commsStatus": "Comms Failed 2020-04-14",
      "controllerStatus": "Auto",
      "spm": 50.0,
      "pumpFillage": 50.0,
      "inferredProduction": 32.5,
      "effectiveRuntimePercentage": 20,
      "cyclesToday": 23.5,
      "structuralLoadPercentage": 23.5,
      "minMaxloadPercentage": 23.5,
      "gearBoxLoadPercentage": 23.5,
      "rodStressPercentage": 23.5,
      "noOfAlerts": 1,
      "wellStatus": "Over Pumping",
      "avgSpm": "5.5 spm",
      "wellState": "Pumping Normal State",
      "pumpCardDiagnistics": "Normal",
      "pumpDisplacement": "278.0 bbls/day",
      "isWellOffline": false,
      "surfaceUnitInformation": "",
      "lastScan": "",
      "gatewayId": "",
      "strokeLengthInInches": 5,
      "tubingHeadPressure": "10psi",
      "casingHeadPressure": "8psi",
      "calculatedPumpIntakePressure": "10psi",
      "currentFluidLoad": 100,
      "downholeCardAreaInSqInch": 25,
      "pumpInfo": {
        "pumpId": "p01",
        "rodDetails": ""
      },
      "pumpDepthInFt": 10,
      "pumpType": "Steel",
      "lastWellTestData": {
        "testGasData": 146,
        "testOil": 46.41,
        "testWater": 82.68,
        "testGross": 109.1,
        "lastReceivedDtTime": "12/02/2023 12:00:00 AM"
      }
    },
    {
      "wellId": 6,
      "wellName": "Apache 24 FED ",
      "dateTime": "2020-04-14 13:14:59",
      "commsStatus": "Comms Established",
      "controllerStatus": "Hand(Manual)",
      "spm": 50.0,
      "pumpFillage": 50.0,
      "inferredProduction": 32.5,
      "effectiveRuntimePercentage": 20,
      "cyclesToday": 23.5,
      "structuralLoadPercentage": 23.5,
      "minMaxloadPercentage": 23.5,
      "gearBoxLoadPercentage": 23.5,
      "rodStressPercentage": 23.5,
      "noOfAlerts": 3,
      "wellStatus": "Under Pumping",
      "avgSpm": "5.5 spm",
      "wellState": "Pumping Normal State",
      "pumpCardDiagnistics": "Normal",
      "pumpDisplacement": "278.0 bbls/day",
      "isWellOffline": false,
      "surfaceUnitInformation": "",
      "lastScan": "",
      "gatewayId": "",
      "strokeLengthInInches": 5,
      "tubingHeadPressure": "10psi",
      "casingHeadPressure": "8psi",
      "calculatedPumpIntakePressure": "10psi",
      "currentFluidLoad": 100,
      "downholeCardAreaInSqInch": 25,
      "pumpInfo": {
        "pumpId": "p01",
        "rodDetails": ""
      },
      "pumpDepthInFt": 10,
      "pumpType": "Steel",
      "lastWellTestData": {
        "testGasData": 146,
        "testOil": 46.41,
        "testWater": 82.68,
        "testGross": 109.1,
        "lastReceivedDtTime": "12/02/2023 12:00:00 AM"
      }
    },
    {
      "wellId": 7,
      "wellName": "Jones 2-15-022BH",
      "dateTime": "2020-04-14 13:14:59",
      "commsStatus": "Comms Established",
      "controllerStatus": "Hand(Manual)",
      "spm": 50.0,
      "pumpFillage": 50.0,
      "inferredProduction": 32.5,
      "effectiveRuntimePercentage": 20,
      "cyclesToday": 23.5,
      "structuralLoadPercentage": 23.5,
      "minMaxloadPercentage": 23.5,
      "gearBoxLoadPercentage": 23.5,
      "rodStressPercentage": 23.5,
      "noOfAlerts": 8,
      "wellStatus": "Over Pumping",
      "avgSpm": "5.5 spm",
      "wellState": "Pumping Normal State",
      "pumpCardDiagnistics": "Normal",
      "pumpDisplacement": "278.0 bbls/day",
      "isWellOffline": false,
      "surfaceUnitInformation": "",
      "lastScan": "",
      "gatewayId": "",
      "strokeLengthInInches": 5,
      "tubingHeadPressure": "10psi",
      "casingHeadPressure": "8psi",
      "calculatedPumpIntakePressure": "10psi",
      "currentFluidLoad": 100,
      "downholeCardAreaInSqInch": 25,
      "pumpInfo": {
        "pumpId": "p01",
        "rodDetails": ""
      },
      "pumpDepthInFt": 10,
      "pumpType": "Steel",
      "lastWellTestData": {
        "testGasData": 146,
        "testOil": 46.41,
        "testWater": 82.68,
        "testGross": 109.1,
        "lastReceivedDtTime": "12/02/2023 12:00:00 AM"
      }
    },
    {
      "wellId": 8,
      "wellName": "Jones 2-15-022BH",
      "dateTime": "2020-04-14 13:14:59",
      "commsStatus": "Comms Established",
      "controllerStatus": "Hand(Manual)",
      "spm": 50.0,
      "pumpFillage": 50.0,
      "inferredProduction": 32.5,
      "effectiveRuntimePercentage": 20,
      "cyclesToday": 23.5,
      "structuralLoadPercentage": 23.5,
      "minMaxloadPercentage": 23.5,
      "gearBoxLoadPercentage": 23.5,
      "rodStressPercentage": 23.5,
      "noOfAlerts": 2,
      "wellStatus": "Over Pumping",
      "avgSpm": "5.5 spm",
      "wellState": "Pumping Normal State",
      "pumpCardDiagnistics": "Normal",
      "pumpDisplacement": "278.0 bbls/day",
      "isWellOffline": false,
      "surfaceUnitInformation": "",
      "lastScan": "",
      "gatewayId": "",
      "strokeLengthInInches": 5,
      "tubingHeadPressure": "10psi",
      "casingHeadPressure": "8psi",
      "calculatedPumpIntakePressure": "10psi",
      "currentFluidLoad": 100,
      "downholeCardAreaInSqInch": 25,
      "pumpInfo": {
        "pumpId": "p01",
        "rodDetails": ""
      },
      "pumpDepthInFt": 10,
      "pumpType": "Steel",
      "lastWellTestData": {
        "testGasData": 146,
        "testOil": 46.41,
        "testWater": 82.68,
        "testGross": 109.1,
        "lastReceivedDtTime": "12/02/2023 12:00:00 AM"
      }
    },
    {
      "wellId": 9,
      "wellName": "Jones 2-15-022BH",
      "dateTime": "2020-04-14 13:14:59",
      "commsStatus": "Comms Established",
      "controllerStatus": "Shutdown",
      "spm": 50.0,
      "pumpFillage": 50.0,
      "inferredProduction": 32.5,
      "effectiveRuntimePercentage": 20,
      "cyclesToday": 23.5,
      "structuralLoadPercentage": 23.5,
      "minMaxloadPercentage": 23.5,
      "gearBoxLoadPercentage": 23.5,
      "rodStressPercentage": 23.5,
      "noOfAlerts": 1,
      "wellStatus": "Optimum Pumping",
      "avgSpm": "5.5 spm",
      "wellState": "Pumping Normal State",
      "pumpCardDiagnistics": "Normal",
      "pumpDisplacement": "278.0 bbls/day",
      "isWellOffline": false,
      "surfaceUnitInformation": "",
      "lastScan": "",
      "gatewayId": "",
      "strokeLengthInInches": 5,
      "tubingHeadPressure": "10psi",
      "casingHeadPressure": "8psi",
      "calculatedPumpIntakePressure": "10psi",
      "currentFluidLoad": 100,
      "downholeCardAreaInSqInch": 25,
      "pumpInfo": {
        "pumpId": "p01",
        "rodDetails": ""
      },
      "pumpDepthInFt": 10,
      "pumpType": "Steel",
      "lastWellTestData": {
        "testGasData": 146,
        "testOil": 46.41,
        "testWater": 82.68,
        "testGross": 109.1,
        "lastReceivedDtTime": "12/02/2023 12:00:00 AM"
      }
    }
  ]
}